version: '3.5'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - ./dist:/usr/share/nginx/html
            - ./php:/usr/share/nginx/html/php
            - ./nginx.conf:/etc/nginx/nginx.conf
        links:
            - db
            - php
    db:    
        image: postgres
        environment:
            POSTGRES_PASSWORD: simple

    php:
        image: php:7-fpm
        volumes:
            - ./php:/usr/share/nginx/html/php