version: '3.5'

services:

  hardware-mania:
    container_name: pw1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4200:4200'
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: simple