version: '3.5'

services:
    web:
        image: nginx:latest
        ports:
        - "8080:80"
        volumes:
        - ./dist:/usr/share/nginx/html
        - ./nginx.conf:/etc/nginx/nginx.conf
        links:
        - db
        - php
    db:    
        image: postgres
        environment:
            POSTGRES_PASSWORD: simple

    php:
        image: php:7-fpm